name: FarTest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16979
title: Far Away
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebf2fc'
    - '#2f3b51'
    - '#060407'
    - '#ea844a'
    - '#a7adb9'
  brandStrength: 0.5958920093253255
  lightness: 0.6900535502936691
  saturation: 0.41723397374153137
  rhythmicContrast: 0.07301324396394193
purpose: []
