name: FarTest
favicon: null
layout_spectrum: 0.1796225542202592
typography_spectrum: 0.2186674694530666
title: Far Away
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5958920093253255
  lightness: 0.6900535502936691
  saturation: 0.41723397374153137
  rhythmicContrast: 0.07301324396394193
purpose: []
